# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python dependencies
COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir mcp[cli]>=1.6.0 requests>=2.32.3

# Copy application code
COPY . .

# Default command
CMD ["python", "main.py"]
